# Generated by Django 6.0.2 on 2026-04-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag_product_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
